a = input('Digite algo...')
print('o tipo primitivo desse valor é', type(a))
print('Só tem espacos?', a.isspace())
print('É um numero?', a.isnumeric())
print('É uma letra?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Esta em maiuscula?', a.isupper())
print('Esta em minuscula?', a.islower())
print('Esta capitalizada?', a.istitle())


a = input('Digite algo: ')
print('O tipo primitivo desse valor é {} '.format(type(a)))
print('Só tem espaços? {} '.format(a.isspace()))
print('É um numero? {} '.format(a.isnumeric()))
print('É alfabetico? {} '.format(a.isalpha()))
print('É alfanumerico? {} '.format(a.isalnum()))
print('Esta em maiusculas? {} '.format(a.isupper()))
print('Esta em minusculas? {} '.format(a.islower()))
print('Esta capitalizada? {} '.format(a.istitle()))